### PR TITLE
boost/math/tools/config.hpp: Cherry pick boostorg/math #729

### LINKED ISSUE #15296: BUG: SciPy 1.7.x build failure on Cygwin
### Describe your issue.

SciPy 1.7.2 and 1.7.3 fail to build from source on Cygwin - https://trac.sagemath.org/ticket/33080

The failures come in through the vendored boost math library. as reported in https://github.com/boostorg/math/pull/727 and https://github.com/boostorg/math/pull/728

### Reproducing Code Example

```python
pip install scipy
```

### Error message

```shell
scipy/stats/_boost/src/beta_ufunc.cxx:3903:46:   required from here
  /opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/var/tmp/sage/build/scipy-1.7.3/src/scipy/_lib/boost/boost/math/tools/promotion.hpp:148:37: error: static assertion failed: Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.
    148 |          BOOST_STATIC_ASSERT_MSG((0 == ::boost::is_same<type, long double>::value), "Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.");
error: Command "g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -DOPENSSL_NO_SSL3=1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.12-1.x86_64/build=/usr/src/debug/python38-3.8.12-1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.12-1.x86_64/src/Python-3.8.12=/usr/src/debug/python38-3.8.12-1 -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -DOPENSSL_NO_SSL3=1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.12-1.x86_64/build=/usr/src/debug/python38-3.8.12-1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.12-1.x86_64/src/Python-3.8.12=/usr/src/debug/python38-3.8.12-1 -D_GNU_SOURCE -DBOOST_MATH_DOMAIN_ERROR_POLICY=ignore_error -DBOOST_MATH_EVALUATION_ERROR_POLICY=user_error -DBOOST_MATH_PROMOTE_DOUBLE_POLICY=false -Iscipy/stats/_boost/include/ -Iscipy/stats/_boost/src/ -I/opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/lib/python3.8/site-packages/numpy/core/include -I/opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/var/tmp/sage/build/scipy-1.7.3/src/scipy/_lib/boost -I/opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/lib/python3.8/site-packages/numpy/core/include -Ibuild/src.cygwin-3.3.3-x86_64-3.8/numpy/distutils/include -I/opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/include -I/usr/include/python3.8 -c scipy/stats/_boost/src/beta_ufunc.cxx -o build/temp.cygwin-3.3.3-x86_64-3.8/scipy/stats/_boost/src/beta_ufunc.o -MMD -MF build/temp.cygwin-3.3.3-x86_64-3.8/scipy/stats/_boost/src/beta_ufunc.o.d -std=c++14 -msse -msse2 -msse3" failed with exit status 1
```

### SciPy/NumPy/Python version information

1.7.x

### PR DESCRIPTION
**Pull request by mkoeppe**
Cherry-picked the header file change from https://github.com/boostorg/math/pull/729

Fixes https://github.com/scipy/scipy/issues/15296

Ref:  https://trac.sagemath.org/ticket/33080

### CODE REVIEW

**Comment by mckib2** [comment]
Thanks @mkoeppe!  I do have a maintenance concern with cherry-picking, see below for potential resolution

@rgommers How do we handle patches with other vendored code?  I assume we want a way to replay these changes on any future updates to this repo we make, so we might need to make some additions to [make_headers.py](https://github.com/scipy/boost-headers-only/blob/main/make_headers.py) to apply a set of patches based on the boost versions.  You tell me -- is that complicating things too much or is that the right amount of complication?

**Comment by mckib2** [comment]
Also just remembered that scipy is not pointing to latest commit -- it's pointing to [2110ce2](https://github.com/scipy/boost-headers-only/tree/2110ce20e59917b85b12059b3ddd8b133549f662).  Let's do a real fix -- I'll do the following:

- "revert" this repo to have its latest commit point at Boost 1.75 headers
- add in machinery to apply patches bases on target Boost versions

Then you'll be able to generate a patch file to be applied rather than manually tracking what has been cherry-picked

**Comment by rgommers** [comment]
That sounds like a good idea. We typically have patch files to go with the vendored libraries, for example:
- `scipy/sparse/linalg/dsolve/SuperLU/scipychanges.patch`
- `scipy/scipy/sparse/linalg/eigen/arpack/ARPACK/README.scipy`

**Comment by mckib2** [comment]
@mkoeppe I think with #6, we're ready to have you generate a patch file and place it in the `patches/` directory.  After that is completed, we'll then need an accompanying PR against SciPy to update the submodule commit

**Comment by mckib2** [comment]
Thanks @mkoeppe, this side LGTM!  Thanks for helping us work through this

**Pull request merged**
