### PR TITLE
ENH: Boost 1.75 and patch application

### PR DESCRIPTION
**Pull request by mckib2**
In support of #5 

- "revert" `main` such that it has the same version of Boost used by SciPy
    - SciPy is built against Boost 1.75, but this repo's main contains Boost 1.76
    - It would be nice for the default GitHub view (main branch at latest commit) to match the Boost version and contents being built in SciPy
    - The majority of the diffs in this PR are reverting from Boost 1.76 to Boost 1.75  
- add mechanism to automatically apply patches during header generation

### CODE REVIEW

**Comment by mckib2** [comment]
@rgommers Probably more useful to browse by commit for this PR -- changes mostly concentrated in generated Boost header files.  The last commit has the interesting bits

**Review by rgommers — COMMENTED** [review]
Thanks @mckib2, this apply-patches mechanism looks good to me.

> "revert" `main` such that it has the same version of Boost used by SciPy

Can you add some detail in the PR description about what is going on with the rest of this diff? Where did it come from and why can we discard it now rather than re-applying some patches?

**Comment by mckib2** [comment]
@rgommers Sorry, I missed your last comment.  I updated PR description -- does that make it more clear why/where those diffs come from?

**Comment by rgommers** [comment]
Thanks @mckib2, only kind of - I am still puzzled about why we have commits in `main` here that we never pointed the SciPy Boost submodule at. Were they just for testing? If so, and you're happy to discard that now, then yes I think we can go ahead and merge this.

**Comment by mckib2** [comment]
> Were they just for testing?

My recollection is hazy, but yes, I believe before we moved the boost-headers-only repo under the SciPy org I had made a commit to main to test out if Boost 1.76 worked with SciPy.  It did not, but looks like I never reverted that commit so it's been there this whole time

**Comment by rgommers** [comment]
Okay thanks, in it goes!

**Pull request merged**
